services:
  api:
    build:
      context: ./service-api-ingestor
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - HOST=0.0.0.0
    networks:
      - logs-network

networks:
  logs-network:
    driver: bridge